# Generated by Django 5.2.3 on 2025-08-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('welcome_message', models.TextField(blank=True)),
                ('background_image', models.ImageField(upload_to='homepage/')),
            ],
        ),
        migrations.CreateModel(
            name='PortalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('dashboard', 'Dashboard'), ('courses', 'Courses'), ('finance', 'Finance'), ('profile', 'Profile'), ('library', 'Library'), ('events', 'Events'), ('help', 'Help & Support')], max_length=50, unique=True)),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/')),
            ],
        ),
    ]
