# Generated by Django 5.2.3 on 2025-08-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='courses_blurb',
            field=models.TextField(blank=True, default='Jump into your courses—grab materials and track progress!'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='courses_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_courses', to='dashboard.portalpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='finance_blurb',
            field=models.TextField(blank=True, default='Stay on top of your fees with ease!'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='finance_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_finance', to='dashboard.portalpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='grades_blurb',
            field=models.TextField(blank=True, default='Check your grades anytime and celebrate your wins!'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='grades_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_grades', to='dashboard.portalpage'),
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='page_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('courses', 'Courses'), ('finance', 'Finance'), ('grades', 'Grades'), ('profile', 'Profile'), ('library', 'Library'), ('events', 'Events'), ('help', 'Help & Support')], max_length=50, unique=True),
        ),
    ]
