# Generated by Django 5.2.3 on 2025-08-15 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_homepage_courses_blurb_homepage_courses_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='courses_blurb',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='courses_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='finance_blurb',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='finance_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='grades_blurb',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='grades_page',
        ),
    ]
