# Generated by Django 5.2.3 on 2025-08-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_homepage_courses_blurb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalpage',
            name='content',
        ),
        migrations.AddField(
            model_name='portalpage',
            name='courses_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='events_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='finance_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='grades_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='help_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='library_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='main_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portalpage',
            name='profile_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portal_images/'),
        ),
        migrations.AlterField(
            model_name='portalpage',
            name='page_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('courses', 'Courses'), ('grades', 'Grades'), ('profile', 'Profile'), ('finance', 'Finance'), ('library', 'Library'), ('events', 'Events'), ('help', 'Help')], max_length=50, unique=True),
        ),
    ]
