# Generated by Django 5.2.3 on 2025-08-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_course_alter_homepage_welcome_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalpage',
            name='image',
        ),
    ]
