# Generated by Django 5.2.3 on 2025-08-16 14:19

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_event_faq_libraryitem_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('admissions', 'Admissions'), ('finance', 'Finance'), ('courses', 'Courses'), ('technical', 'Technical'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
